development:
  adapter: postgresql
  encoding: unicode
  database: forum_development
  pool: 5
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: forum_test
  pool: 5
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: forum_production
  pool: 5
  password:
