development:
  adapter: postgresql
  encoding: unicode
  database: forum_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: forum_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: forum_production
  pool: 5
  username: postgres
  password: postgres
