#source 'https://rubygems.org'
source 'http://ruby.taobao.org'

gem 'rails', '4.0.0'
gem 'sqlite3'

gem 'sass-rails'
gem 'coffee-rails'
gem 'uglifier'

gem 'jquery-rails'

gem 'paper_trail',  github: 'airblade/paper_trail', branch: 'rails4'

gem 'actionpack-page_caching'
gem 'actionpack-action_caching'

group :test, :development do
  gem "rspec-rails"
end

group :test do
  gem "factory_girl_rails"
  gem "capybara"
  gem "guard-rspec"
  gem "rb-fsevent"
end
