#source 'https://rubygems.org'
source 'http://ruby.taobao.org'

ruby '2.0.0'
gem 'rails', '4.0.0'
gem 'mysql2'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'omniauth-github'
gem 'slim-rails'
gem 'bootstrap-sass'
gem 'simple_form', '~> 3.0.0.rc'
gem 'bootstrap_helper'
gem 'settingslogic'
gem 'cancan'
gem 'redcarpet'
gem 'md_emoji'

gem 'rack-mini-profiler'
gem 'cache_query', github: 'zlx/cache_query'

group :test, :development do
  gem 'pry-debugger'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
end

group :doc do
  gem 'sdoc', require: false
end

group :development do
  gem 'thin'
  # guard start
  gem 'guard-rspec'
end

group :production do
  gem 'rails_12factor'
  gem 'pg'
  gem 'taps'
end

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the app server
gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
