source 'http://ruby.taobao.org'

gem 'rails', '4.0.0' 
gem 'sqlite3' 
gem 'sass-rails',   '~> 4.0.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~>1.2'
gem 'pry-debugger'

# To use ActiveModel has_secure_password
gem 'bcrypt-ruby', '~> 3.0.0'
gem 'protected_attributes'
