Product.create!(name: "Settlers of Catan", price: 34.95)
Product.create!(name: "Red Shirt", price: 12.49)
Product.create!(name: "Oak Coffee Table", price: 223.99)
Product.create!(name: "Technodrome", price: 27.99)
Product.create!(name: "Oh's Cereal", price: 3.95)
Product.create!(name: "Game Console", price: 299.95)
Product.create!(name: "Video Game", price: 29.95)
Product.create!(name: "Lawn Chair", price: 34.99)
Product.create!(name: "Dog Toy Bone", price: 2.99)
Product.create!(name: "Heated Blanket", price: 27.95)
Product.create!(name: "Flux Capacitor", price: 19.55)
Product.create!(name: "Chocolate Pie", price: 3.14)
Product.create!(name: "Acoustic Guitar", price: 1024.00)
Product.create!(name: "Model Enterprise", price: 27.99)
Product.create!(name: "Agricola", price: 45.99)
Product.create!(name: "Stone Age", price: 34.99)
Product.create!(name: "7 Wonders", price: 28.75)
Product.create!(name: "Seafarers of Catan", price: 19.95)
Product.create!(name: "Knights of Catan", price: 19.95)
Product.create!(name: "Answer to Everything", price: 42.00)
Product.create!(name: "Box Kite", price: 63.00)
Product.create!(name: "1000 Piece Jigsaw Puzzle", price: 14.99)
Product.create!(name: "Rubber Ducky", price: 4.75)
Product.create!(name: "Unicorn Action Figure", price: 8.75)
Product.create!(name: "Rack", price: 32.49)
Product.create!(name: "Model Train Rails", price: 45.00)
Product.create!(name: "CanCan Music Record", price: 2.99)
